"""Add username and repo fields

Revision ID: 0a74d7b98767
Revises: 
Create Date: 2026-04-12 13:25:51.143448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a74d7b98767'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tree_entries_tree_hash'), table_name='tree_entries')
    op.drop_table('tree_entries')
    op.drop_table('branches')
    op.drop_table('commits')
    op.drop_index(op.f('ix_blobs_hash'), table_name='blobs')
    op.drop_table('blobs')
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.create_table('blobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('repo_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('r2_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], name=op.f('blobs_repo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('blobs_pkey'))
    )
    op.create_index(op.f('ix_blobs_hash'), 'blobs', ['hash'], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('repo_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parent_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tree_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], name=op.f('commits_repo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('commits_pkey'))
    )
    op.create_table('branches',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('repo_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('head_commit_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['head_commit_id'], ['commits.id'], name=op.f('branches_head_commit_id_fkey')),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], name=op.f('branches_repo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('branches_pkey'))
    )
    op.create_table('tree_entries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('repo_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tree_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('blob_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], name=op.f('tree_entries_repo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tree_entries_pkey'))
    )
    op.create_index(op.f('ix_tree_entries_tree_hash'), 'tree_entries', ['tree_hash'], unique=False)
    # ### end Alembic commands ###
