"""add stars table and forked_from to repositories

Revision ID: 683fd9eb766e
Revises: a6fc03bc2718
Create Date: 2026-04-27 23:45:24.235191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683fd9eb766e'
down_revision: Union[str, Sequence[str], None] = 'a6fc03bc2718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('forked_from_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'repositories', 'repositories', ['forked_from_id'], ['id'])
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['google_id'], unique=True)
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_column('repositories', 'forked_from_id')
    # ### end Alembic commands ###
